### PR TITLE
Fix: missing licensing

### PR DESCRIPTION
**Pull request by dragonmux**
## Description

In this PR we address the missing licensing for the contents of the repository. After asking @Qyriad we came to the agreement to license this library in the same way as bmputil.

She has been tagged to get her public agreement to how this has been done.

## Closing issues

### CODE REVIEW

**Comment by esden** [comment]
@Qyriad For the record, can you confirm for us here that it is ok to add the mixed Apache/MIT licensing to this project? :)

**Review by Qyriad — APPROVED** [review]

**Comment by Qyriad** [comment]
Yep! I confirm that I agree to dual licensing under the Apache and MIT licenses for this project, and that @dragonmux and I are in complete agreement in this.

**Comment by Qyriad** [comment]
Apologies for the missing license in the first place!

**Comment by esden** [comment]
@Qyriad thank you very much!

**Review by esden — APPROVED** [review]
LGTM

**Pull request merged**
